export const CANVAS_CELL_LENGTH = 15
export const COUNT_ROWS = 10
export const COUNT_COLUMNS = 10
export const CANVAS_HEIGHT = COUNT_ROWS * CANVAS_CELL_LENGTH
export const CANVAS_WIDTH = COUNT_COLUMNS * CANVAS_CELL_LENGTH